### PR TITLE
feat(solr): Add ability to inject options to the request

### PR DESCRIPTION
**Pull request by niezgoda**
Currently there is no ability to pass additional arguments to the http/https request.

The option to add (for example) ssl parameters (like ca, cert, key) is neccesarry in multiple cases.

### CODE REVIEW

**Review by julianlam — DISMISSED** [review]
Can you revert all of the whitespace changes, or re-open them into a new pull request?

**Comment by niezgoda** [comment]
> Can you revert all of the whitespace changes, or re-open them into a new pull request?

I have reverted all the changes to the whitespaces/formatting.

**Comment by julianlam** [comment]
As this is an API change (introducing a new argument to the `createClient` method), I would not feel comfortable merging outright, and would defer to @lbdremy

**Comment by lbdremy** [comment]
Hello,

This change does not break the API, so no worries for me. You can merge @julianlam and publish a new minor version 0.8.0.

**Comment by kibertoad** [comment]
Released in 0.8.0

**Pull request merged**
