### PR TITLE
Implement The TermsComponent

### PR DESCRIPTION
**Pull request by godong9**
Implement The TermsComponent.

Test need to modify "solrconfig.xml".

http://wiki.apache.org/solr/TermsComponent

### CODE REVIEW

**Comment by luketaverne** [comment]
This looks good. Nice work! Could you revise a few things before we merge this?

* The https://wiki.apache.org/solr/ pages are for old versions of Solr, and I'm unsure whether they are still maintained. Can you **change these links to the relevant pages on the Solr 5 [cwiki](https://cwiki.apache.org/confluence/display/solr/Apache+Solr+Reference+Guide)**? We're aiming for full support of Solr 5, so having the Solr 5 docs from this point forward is desired.
* Your test is failing because you're examining the `data.terms` object. The test platform (as far as I know, correct me if I'm wrong here @lbdremy @nicolasembleton), doesn't contain any example docs. So **your `assert.deepEqual()` should examine `data.responseHeader.params` instead**. Then the tests will pass.
* Formatting of the "Terms Component" wiki page that was copied into the test should be removed. A link to the cwiki page will do just fine, and look cleaner.
* Formatting of the options array on **line 55 of terms-query-test.js**. Extra space should be removed.

Aside from these small things, your implementation works well in my testing. Thanks for contributing!

**Comment by godong9** [comment]
Thank you for your reply.

I changed something but ci still failed.

1. TermsComponent didn’t change on solr5. 
The Terms Component The Terms Component provides access to the indexed terms in a field and the number of documents that match each term. This can be useful for building an auto-suggest feature or any other feature that operates at the term level instead of the search or document level. Retrieving terms in index order is very fast since the implementation directly uses Lucene's TermEnum to iterate over the term dictionary. In a sense, this search component provides fast field-faceting over the whole index, not restricted by the base query or any filters. The document frequencies returned are the number of documents that match the term, including any documents that have been marked for deletion but not yet removed from the index. (347page in apache-solr-ref-guide-5.3.pdf)

2. Solr in CI dosen’t support terms component, so that problem occurred.
http://localhost:8983/solr/collection1/terms?terms.fl=title&terms.lower=s
This working good in my local pc, but ci test still failed. It should be changed “solrconfig.xml".

<searchComponent name="terms" class="solr.TermsComponent"/>

Defining the Terms Component Defining the Terms search component is straightforward: simply give it a name and use the class solr.TermsC omponent. This makes the component available for use, but by itself will not be useable until included with a request handler.

3. Change complete.

4. I change formatting, but code still looks like that by github. 
https://github.com/godong9/solr-node-client/blob/master/test/mlt-query-test.js
This file shows same style.

Please check 1, 2, 3, 4 items and reply.

**Comment by luketaverne** [comment]
Okay, looks good. I would still like you to change the links to the cwiki versions though, even though nothing is currently different content-wise between the two pages. It's always good to point to the most recent versions of manuals.

I didn't notice this at first, but I think having both `query.terms(options)` and then `client.terms(query, function(...` may be a bit confusing to users. I think `query.terms(options)` is fine, since you're defining a terms query. I feel that one of them needs to be named differently to avoid confusion. Either way, this is a good time to talk about how we're going to define these types of queries moving forward. "What do we do when the user needs a specific Query Handler for a query?" @nicolasembleton, @lbdremy I'd like your feedback on this implementation naming if you have time. Later on, we should have a different thread to talk about how to design these kinds of things moving forward, maybe for the 1.0 release.

**Comment by nicolasembleton** [comment]
I definitely lean toward that: `I think query.terms(options) is fine, since you're defining a terms query.` 
If you use client.terms() that adds a term for a query, it's indeed confusing. 

@luketaverne Yes, definitely in for a design / naming convention meeting. Been under a lot lately due to job change so have been pretty much unavailable. But early on next year let's go with that. 

@godong9 You're good with that? You did a great work for this PR, would love to have it going through for 0.7.

**Comment by godong9** [comment]
@nicolasembleton Yes, I'm good. I agree client.terms() that indeed confusing.

**Comment by nicolasembleton** [comment]
@godong9 Mind pushing that last bit of change? I didn't see the commit for `query.terms` change. Then I'll merge because it's really good work.

**Comment by godong9** [comment]
@nicolasembleton Sorry I forgot this things. I change "client.terms" to "client.termsSearch".

**Pull request merged**
