### PR TITLE
Drop support for deprecated Node versions

### PR DESCRIPTION
**Pull request by kibertoad**
This enables us to use up-to-date libraries and modern JavaScript syntax.

### CODE REVIEW

**Review by lbdremy — APPROVED** [review]
Since we are going drop nodejs versions support, we should bump the major version in the next release (anyway the version 1.0.0 is long overdue ^^), also I remember we were using conventional commit some times ago, it helps generate the changelog, and make semantic versioning easier, easy to automate for both concerns changelog and versioning. See https://www.conventionalcommits.org/en/v1.0.0/ and https://github.com/conventional-changelog/standard-version for the tooling and https://github.com/conventional-changelog/commitlint for commitlint.

**Comment by rudolfbyker** [comment]
I'm also working on some relentless refactoring, and it would be great to get that in before 1.0.0, because it just makes everything much easier if I'm allowed to change a few method names on `Client.prototype`.

**Review by rudolfbyker — APPROVED** [review]

**Comment by kibertoad** [comment]
@lbdremy On topic of conventional commits: while it makes sense to have it as a soft requirement, I don't mind maintaining changelog by hand. In my experience enforcing particular commit style always was a huge hassle and source of endless frustration for people trying to contribute.

**Comment by kibertoad** [comment]
@rudolfbyker Yup! Let's make next version a 1.0.0, and delay its release until we are done with breaking major stuff :)

**Comment by rudolfbyker** [comment]
OK, so refactoring for v1, then typescript and more refactoring for v2?

**Comment by kibertoad** [comment]
@rudolfbyker Sounds good! Any chance you could also cover at least a part of https://github.com/lbdremy/solr-node-client/issues/251 while refactoring?

**Comment by rudolfbyker** [comment]
I tried that, but it became too complex. I'll do it as a separate step after what I'm doing now. But it's definitely on my list!

**Comment by rudolfbyker** [comment]
Speaking of refactoring, I think that doing things like 

```js
Client.prototype.commit = function(options, callback) {
  if (typeof options === 'function') {
    callback = options;
    options = {};
  }
```
is an anti-pattern. I know it's very common in the JS world, but it's still bad. It makes for a sloppy contract, and serves as a not-fun bonus multiplier on all of the possible ways in which the code can break. It also increases boilerplate code, and forces you to write more tests than necessary.

I you all agree with me, I would like to address this in my refactoring, too. It will also help to smooth the transition into Typescript.

**Comment by kibertoad** [comment]
@rudolfbyker I agree. My personal preference would be:
* Prefer promise/async-await solutions over callbacks where possible;
* Use classes over prototypes where possible, but prefer purely functional style where statefulness is not needed;
* Avoid polymorphic function parameters as much as possible (not only they are confusing, they also destroy performance by obstructing optimization).

**Comment by rudolfbyker** [comment]
So I'm almost done with my refactoring, but I can't get the last few unit tests up and running again... Getting this error: "Solr instance is not running in SolrCloud mode". Any idea what that means? It happens on all tests under `describe('Collection', ...)`, i.e. the tests for `Client.prototype.executeCollection`.

**Comment by kibertoad** [comment]
@rudolfbyker SolrCloud mode is just a distributed mode for running Solr server, I don't think that should be affecting anything. Are you sure that is the actual error failing tests? Can you try creating PR so that I could check what CI outputs?

**Comment by kibertoad** [comment]
See http://mail-archives.apache.org/mod_mbox/lucene-solr-user/201807.mbox/%3CCAPCX2-+jojXrWvPSPiBR_xwphdpk+yPM2HYLojX2rqRTKMGm9g@mail.gmail.com%3E
Wonder if you are running your Solr instance differently from how CI is, or creating collections differently.

**Comment by rudolfbyker** [comment]
I'm running it like this: `npm run solr:current:start`

But I just discovered something: When I run `npm run test:current` from the command line, everything passes. Running the same tests in Intellij IDEA causes the `Collection` tests to fail. Not sure why. And also not super important for now.

One more thing: I think we could remove the volumes from our docker-compose definitions. We would not want to persist any data when stopping and starting the test containers.

**Comment by kibertoad** [comment]
@rudolfbyker Wouldn't be surprised if tests are leaking state and some of the tests rely on some other tests having been run beforehand. Which is bad and should be fixed, if that is the case.

**Pull request merged**
