### PR TITLE
Use "prettier/recommended" instead of rolling our own

### PR DESCRIPTION
**Pull request by rudolfbyker**
This is just a suggestion to standardize the code style as much as possible, but it will cause a lot of merge conflicts. Feel free to reject it or make alternative suggestions. However, accepting this PR is probably the fastest way forward into clean code.

### CODE REVIEW

**Comment by rudolfbyker** [comment]
To clarify, I only changed eslint and prettier config files. The rest of the changes were done by eslint.

**Comment by kibertoad** [comment]
Sounds good! Can you add prettier config to enforce arrow parens always, and singular quotes, though?

**Comment by rudolfbyker** [comment]
I could, but why single quotes? Why not just the default?

**Comment by kibertoad** [comment]
no big difference, but
a) less changes, hence less conflicts
b) more popular in OSS js projects
c) matter of personal preference :-D

**Comment by rudolfbyker** [comment]
a) Good point
b) Debatable
c) Sure why not :man_shrugging:

**Comment by rudolfbyker** [comment]
It turns out prettier already turns `x => null` into `(x) => null`. So the only change needed is the choice of quotes.

**Review by kibertoad — APPROVED** [review]

**Pull request merged**
