### PR TITLE
Update npm dependencies

### PR DESCRIPTION
**Pull request by HaroldPutman**
Apply all npm audit fixes.

### CODE REVIEW

**Comment by HaroldPutman** [comment]
```
                       === npm audit security report ===

# Run  npm install request@2.88.0  to resolve 4 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ request                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ request > hawk > boom > hoek                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ request                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ request > hawk > cryptiles > boom > hoek                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ request                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ request > hawk > hoek                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ request                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ request > hawk > sntp > hoek                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm install --save-dev mocha@5.2.0  to resolve 3 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > debug                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > glob > minimatch                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > growl                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/146                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 7 vulnerabilities (1 low, 4 moderate, 1 high, 1 critical) in 110 scanned packages
  run `npm audit fix` to fix 4 of them.
  3 vulnerabilities require semver-major dependency updates.

**Comment by HaroldPutman** [comment]
Of course, upgrading mocha means it won't run on ancient version of node. <4

**Comment by vaneetkaur** [comment]
@HaroldPutman Do you think this will get merged anytime soon?

**Comment by vaneetkaur** [comment]
@lbdremy I'd like this to be merged. Could I help in anyway?

**Comment by julianlam** [comment]
@lbdremy -- would be lovely if you could merge this in

**Comment by sandeep-barla** [comment]
@lbdremy , we need this to be merged. When can we expect it to be done?

**Comment by vaneetkaur** [comment]
@julianlam @sandeep-barla I would recommend that you fork the repo and upgrade.

**Comment by julianlam** [comment]
We can, of course, but it is not a trivial task because by doing so you become the de facto maintainer of the package once it is published to npm (assuming you want to take on the role of superceding this package).

Perhaps we can all do it, along with @HaroldPutman :thinking:

**Comment by lbdremy** [comment]
Hi @HaroldPutman and @julianlam I can add you as contributor in both github repo and npm package so you can publish. I have opened an issue a while ago to ask for contributors https://github.com/lbdremy/solr-node-client/issues/133

**Comment by vaneetkaur** [comment]
I am happy to help as well @lbdremy

**Comment by lbdremy** [comment]
hello @vaneetkaur @julianlam, 

cool, I sent an invite to both of you on this repo to become collaborator, let me know when you want npm publish access.

**Comment by julianlam** [comment]
Wonderful! My npm account: https://www.npmjs.com/~julianlam

Thanks @lbdremy

**Comment by julianlam** [comment]
Hi @lbdremy -- just following up on npm publish rights.

**Comment by lbdremy** [comment]
invitation sent @julianlam

**Comment by julianlam** [comment]
I don't see the invitation, actually :thinking: Can you not just run `npm owner add julianlam solr-client`?

**Comment by lbdremy** [comment]
Okay weird, should be good now.

Le mer. 4 sept. 2019 à 17:25, Julian Lam <notifications@github.com> a
écrit :

**Comment by julianlam** [comment]
Hi all, sorry for the delay. v0.7.1 published to npm for general consumption.

**Pull request merged**
