### PR TITLE
Update Package.json dependencies, according tests, activate solrVersion, facet.pivot, add helpers for standardization

### PR DESCRIPTION
**Pull request by nicolasembleton**
Some packages are getting very old. I've updated them and tested, then updated the tests to match the new requirements (mainly for bignumber.js and solr5 multi-valued constraints)

### CODE REVIEW

**Comment by nicolasembleton** [comment]
@luketaverne Would you mind giving a look to that? I had to activate solrVersion support to not break tests and make that some features that are 4.0 only will not be ran when the solrVersion is not over 4. I'll add doc to explain how to specify the solr version so it activates the features if needed. I also updated the piece of code where you change the URL depending on the solrVersion. So now we can support fine-grained version-specific features. 
I've activated facet.pivot feature, and updated the package.json to latest dependencies. 
Apologies for the size and non-homogeneity of the Pull Request. I'll push Pull Requests as I work once this one is merged.

Finally I think that this PR will validate the trigger to 0.6. (Will add some documentation)

**Comment by luketaverne** [comment]
Yes, we definitely need some kind of version support. Doesn't it make more sense to pass the solrVersion to the Client constructor though? It's the Client (ie the installed version of Solr) that has a version. This way, the query format doesn't change when a user upgrades Solr. They won't need to check every query for solrVersion and change it, only the Client constructor. 

I actually added something like this to lib/solr.js last month. [lib/solr.js Line 47](https://github.com/lbdremy/solr-node-client/blob/master/lib/solr.js#L47). It was a quick fix for the UPDATE_JSON_HANDLER for Solr v4.0 and up. Is it possible to use this existing method? Does it make more sense to include in the Client constructor?

**Comment by nicolasembleton** [comment]
@luketaverne Yes it is actually using what you did and centralizing it + standardizing it so we can easily relate to specific version (eg 3.2, 4.0, 4.10, 5.1, etc...). It's passed to the createClient() as a property. Like you did. 
I've just added a version helper that centralizes the definitions and helps to deal with that without making it too hard/obfuscated to re-use, and defaulted to 3.2 so we keep our support promise. 
Also added some docs for that too (in the comment and in the readme). 
Makes sense?

**Comment by luketaverne** [comment]
Ahh okay, I see. My apologies for not reading thoroughly enough! I saw the query constructor containing the solrVersion and thought it was being passed as a query option.

I think this is a really good way to do this. The Client contains the info about its version, tells the Query what version it is, and the Query modifies its format to comply. Nice work!

**Comment by nicolasembleton** [comment]
No problem. Actually I also realized what you meant and yes, wanted to mention exactly what you just said. It's being passed down to the query at createQuery() time by the client itself so we can build granular and version-dependant query :) 

Thanks for the words. I'll pull that later today and compile the 0.6 version if you're all good. I've also updated the docs in gh-pages branch. Will PR them out.

**Comment by luketaverne** [comment]
Sounds good! Need me to do anything in the meantime?

**Comment by nicolasembleton** [comment]
I think preparing some small documentation on collection admin would be great. Mainly sample code. I'll add that in the Codex doc and re-generate it so it'll generate it based on your code + code comments.

**Comment by luketaverne** [comment]
Okay will do. Where do you want me to put the docs?

**Comment by luketaverne** [comment]
I'm still preparing some small docs on the collections operations.

@nicolasembleton, just a small thing, you left the 'e' off the end of my username/ last name in the docs. I could fix it myself, but I don't want to passive-aggressively commit over the top of something you just changed :)

**Comment by nicolasembleton** [comment]
Apologies @luketaverne ... I will fix that!

**Pull request merged**
